version: '3.8'

services:
  # PostgreSQL Database for Development
  postgres:
    image: postgres:15-alpine
    container_name: review_analyzer_db_dev
    environment:
      POSTGRES_DB: review_analyzer
      POSTGRES_USER: review_user
      POSTGRES_PASSWORD: review_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U review_user -d review_analyzer"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - review_analyzer_dev_network

volumes:
  postgres_dev_data:

networks:
  review_analyzer_dev_network:
    driver: bridge 